import React from 'react'
import Head from 'next/head';
import styles from '../styles/Home.module.css'
function about() {
  return (
    <div>
        <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
        <h1>About Page</h1>
    </div>
  )
}

export default about